export const FETCH_WITHDRAWAL_DATA_REQUEST = 'FETCH_WITHDRAWAL_DATA_REQUEST';
export const FETCH_WITHDRAWAL_DATA_SUCCESS = 'FETCH_WITHDRAWAL_DATA_SUCCESS';
export const FETCH_WITHDRAWAL_DATA_FAILURE = 'FETCH_WITHDRAWAL_DATA_FAILURE';
export const SET_SELECTED_METHOD = 'SET_SELECTED_METHOD';
export const RESET_WITHDRAWAL = 'RESET_WITHDRAWAL'; 